export const DUMMY_DATA_ALERTS = [
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: AMARAVATI',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AMARAVATI, ANDHRA PRADESH',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: AMARAVATI',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AMARAVATI, ANDHRA PRADESH',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: AMARAVATI',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AMARAVATI, ANDHRA PRADESH',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: AMARAVATI',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AMARAVATI, ANDHRA PRADESH',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: AMARAVATI',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AMARAVATI, ANDHRA PRADESH',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: ITANAGAR',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'ITANAGAR, ARUNACHAL PRADESH',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: ITANAGAR',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'ITANAGAR, ARUNACHAL PRADESH',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: ITANAGAR',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'ITANAGAR, ARUNACHAL PRADESH',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: ITANAGAR',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'ITANAGAR, ARUNACHAL PRADESH',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: ITANAGAR',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'ITANAGAR, ARUNACHAL PRADESH',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: DISPUR',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'DISPUR, ASSAM',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: DISPUR',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'DISPUR, ASSAM',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: DISPUR',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'DISPUR, ASSAM',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: DISPUR',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'DISPUR, ASSAM',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: DISPUR',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'DISPUR, ASSAM',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: PATNA',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'PATNA, BIHAR',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: PATNA',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'PATNA, BIHAR',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: PATNA',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'PATNA, BIHAR',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: PATNA',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'PATNA, BIHAR',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: PATNA',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'PATNA, BIHAR',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: RAIPUR',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'RAIPUR, CHHATTISGARH',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: RAIPUR',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'RAIPUR, CHHATTISGARH',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: RAIPUR',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'RAIPUR, CHHATTISGARH',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: RAIPUR',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'RAIPUR, CHHATTISGARH',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: RAIPUR',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'RAIPUR, CHHATTISGARH',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: PANAJI',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'PANAJI, GOA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: PANAJI',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'PANAJI, GOA',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: PANAJI',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'PANAJI, GOA',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: PANAJI',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'PANAJI, GOA',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: PANAJI',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'PANAJI, GOA',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: GANDHINAGAR',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'GANDHINAGAR, GUJARAT',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: GANDHINAGAR',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'GANDHINAGAR, GUJARAT',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: GANDHINAGAR',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'GANDHINAGAR, GUJARAT',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: GANDHINAGAR',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'GANDHINAGAR, GUJARAT',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: GANDHINAGAR',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'GANDHINAGAR, GUJARAT',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: CHANDIGARH',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHANDIGARH, HARYANA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: CHANDIGARH',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHANDIGARH, HARYANA',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: CHANDIGARH',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHANDIGARH, HARYANA',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: CHANDIGARH',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHANDIGARH, HARYANA',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: CHANDIGARH',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHANDIGARH, HARYANA',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: SHIMLA',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'SHIMLA, HIMACHAL PRADESH',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: SHIMLA',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'SHIMLA, HIMACHAL PRADESH',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: SHIMLA',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'SHIMLA, HIMACHAL PRADESH',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: SHIMLA',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'SHIMLA, HIMACHAL PRADESH',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: SHIMLA',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'SHIMLA, HIMACHAL PRADESH',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: RANCHI',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'RANCHI, JHARKHAND',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: RANCHI',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'RANCHI, JHARKHAND',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: RANCHI',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'RANCHI, JHARKHAND',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: RANCHI',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'RANCHI, JHARKHAND',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: RANCHI',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'RANCHI, JHARKHAND',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: BENGALURU',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BENGALURU, KARNATAKA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: BENGALURU',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BENGALURU, KARNATAKA',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: BENGALURU',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BENGALURU, KARNATAKA',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: BENGALURU',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BENGALURU, KARNATAKA',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: BENGALURU',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BENGALURU, KARNATAKA',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: THIRUVANANTHAPURAM',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'THIRUVANANTHAPURAM, KERALA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: THIRUVANANTHAPURAM',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'THIRUVANANTHAPURAM, KERALA',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: THIRUVANANTHAPURAM',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'THIRUVANANTHAPURAM, KERALA',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: THIRUVANANTHAPURAM',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'THIRUVANANTHAPURAM, KERALA',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: THIRUVANANTHAPURAM',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'THIRUVANANTHAPURAM, KERALA',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: BHOPAL',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHOPAL, MADHYA PRADESH',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: BHOPAL',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHOPAL, MADHYA PRADESH',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: BHOPAL',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHOPAL, MADHYA PRADESH',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: BHOPAL',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHOPAL, MADHYA PRADESH',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: BHOPAL',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHOPAL, MADHYA PRADESH',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: MUMBAI',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'MUMBAI, MAHARASHTRA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: IMPHAL',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'IMPHAL, MANIPUR',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: IMPHAL',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'IMPHAL, MANIPUR',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: IMPHAL',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'IMPHAL, MANIPUR',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: IMPHAL',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'IMPHAL, MANIPUR',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: IMPHAL',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'IMPHAL, MANIPUR',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: SHILLONG',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'SHILLONG, MEGHALAYA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: SHILLONG',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'SHILLONG, MEGHALAYA',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: SHILLONG',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'SHILLONG, MEGHALAYA',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: SHILLONG',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'SHILLONG, MEGHALAYA',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: SHILLONG',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'SHILLONG, MEGHALAYA',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: AIZAWL',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AIZAWL, MIZORAM',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: AIZAWL',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AIZAWL, MIZORAM',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: AIZAWL',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AIZAWL, MIZORAM',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: AIZAWL',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AIZAWL, MIZORAM',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: AIZAWL',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AIZAWL, MIZORAM',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: KOHIMA',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'KOHIMA, NAGALAND',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: KOHIMA',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'KOHIMA, NAGALAND',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: KOHIMA',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'KOHIMA, NAGALAND',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: KOHIMA',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'KOHIMA, NAGALAND',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: KOHIMA',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'KOHIMA, NAGALAND',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: BHUBANESWAR',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHUBANESWAR, ODISHA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: BHUBANESWAR',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHUBANESWAR, ODISHA',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: BHUBANESWAR',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHUBANESWAR, ODISHA',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: BHUBANESWAR',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHUBANESWAR, ODISHA',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: BHUBANESWAR',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHUBANESWAR, ODISHA',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: CHANDIGARH',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHANDIGARH, PUNJAB',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: CHANDIGARH',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHANDIGARH, PUNJAB',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: CHANDIGARH',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHANDIGARH, PUNJAB',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: CHANDIGARH',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHANDIGARH, PUNJAB',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: CHANDIGARH',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHANDIGARH, PUNJAB',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: JAIPUR',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'JAIPUR, RAJASTHAN',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: JAIPUR',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'JAIPUR, RAJASTHAN',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: JAIPUR',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'JAIPUR, RAJASTHAN',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: JAIPUR',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'JAIPUR, RAJASTHAN',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: JAIPUR',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'JAIPUR, RAJASTHAN',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: GANGTOK',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'GANGTOK, SIKKIM',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: GANGTOK',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'GANGTOK, SIKKIM',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: GANGTOK',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'GANGTOK, SIKKIM',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: GANGTOK',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'GANGTOK, SIKKIM',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: GANGTOK',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'GANGTOK, SIKKIM',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: CHENNAI',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHENNAI, TAMIL NADU',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: CHENNAI',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHENNAI, TAMIL NADU',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: CHENNAI',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHENNAI, TAMIL NADU',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: CHENNAI',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHENNAI, TAMIL NADU',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: CHENNAI',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'CHENNAI, TAMIL NADU',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: HYDERABAD',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'HYDERABAD, TELANGANA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: HYDERABAD',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'HYDERABAD, TELANGANA',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: HYDERABAD',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'HYDERABAD, TELANGANA',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: HYDERABAD',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'HYDERABAD, TELANGANA',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: HYDERABAD',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'HYDERABAD, TELANGANA',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: AGARTALA',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AGARTALA, TRIPURA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: AGARTALA',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AGARTALA, TRIPURA',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: AGARTALA',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AGARTALA, TRIPURA',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: AGARTALA',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AGARTALA, TRIPURA',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: AGARTALA',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'AGARTALA, TRIPURA',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: LUCKNOW',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'LUCKNOW, UTTAR PRADESH',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: LUCKNOW',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'LUCKNOW, UTTAR PRADESH',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: LUCKNOW',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'LUCKNOW, UTTAR PRADESH',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: LUCKNOW',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'LUCKNOW, UTTAR PRADESH',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: LUCKNOW',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'LUCKNOW, UTTAR PRADESH',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: DEHRADUN',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'DEHRADUN, UTTARAKHAND',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: DEHRADUN',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'DEHRADUN, UTTARAKHAND',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: DEHRADUN',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'DEHRADUN, UTTARAKHAND',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: DEHRADUN',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'DEHRADUN, UTTARAKHAND',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: DEHRADUN',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'DEHRADUN, UTTARAKHAND',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FIRE ALERT: KOLKATA',
    description: 'Major fire incident risk in dense urban zone.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'KOLKATA, WEST BENGAL',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR FLOOD ALERT: KOLKATA',
    description: 'Heavy rainfall causing waterlogging and disruption.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'KOLKATA, WEST BENGAL',
    alertLevel: 'Orange',
    eventType: 'FLOOD',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR HEATWAVE ALERT: KOLKATA',
    description: 'Extreme temperatures posing public health risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'KOLKATA, WEST BENGAL',
    alertLevel: 'Orange',
    eventType: 'HEATWAVE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STORM ALERT: KOLKATA',
    description: 'Thunderstorm activity causing temporary disruption.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'KOLKATA, WEST BENGAL',
    alertLevel: 'Yellow',
    eventType: 'STORM',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-${Math.random().toString(36).substr(2, 9)}`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: KOLKATA',
    description: 'Old infrastructure poses collapse risk.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'KOLKATA, WEST BENGAL',
    alertLevel: 'Orange',
    eventType: 'STRUCTURAL FAILURE',
    lat: 20.0,
    lon: 77.0,
  },
  {
    id: `dummy-dummy-xu5g0r36y`,
    title: 'MAJOR FIRE ALERT: MIRA BHAYANDER',
    description: 'Two minors and a man died in a fire. Massive fire at godown near Pleasant Park with multiple cylinder blasts reported.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'MIRA BHAYANDER, MAHARASHTRA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 19.2,
    lon: 72.9,
  },
  {
    id: `dummy-dummy-zjv7m5n7n`,
    title: 'MAJOR SECURITY ALERT: MIRA BHAYANDER',
    description: 'Maharashtra ATS is now piecing together the life of suspects in the region.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'MIRA BHAYANDER, MAHARASHTRA',
    alertLevel: 'Orange',
    eventType: 'SECURITY',
    lat: 19.2,
    lon: 72.9,
  },
  {
    id: `dummy-dummy-4cka3yt26`,
    title: 'MAJOR FIRE ALERT: MANPADA, THANE',
    description: 'Forest fire broke out near Manpada border of Sanjay Gandhi National Park. Required joint action from TMC and Forest Dept.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'MANPADA, THANE, MAHARASHTRA',
    alertLevel: 'Orange',
    eventType: 'FIRE',
    lat: 19.2,
    lon: 72.9,
  },
  {
    id: `dummy-dummy-wq6qx3b2v`,
    title: 'MAJOR FIRE ALERT: BADLAPUR, THANE',
    description: 'Industrial fire at a dyeing unit intensified due to cloth stock and chemical drums. Major property damage.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BADLAPUR, THANE, MAHARASHTRA',
    alertLevel: 'Red',
    eventType: 'FIRE',
    lat: 19.2,
    lon: 72.9,
  },
  {
    id: `dummy-dummy-nhf7bsx6i`,
    title: 'MAJOR STRUCTURAL FAILURE ALERT: MAJIWADA, THANE',
    description: 'Building slab collapsed inside old residential building. Entire building evacuated.',
    severity: 'high',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'MAJIWADA, THANE, MAHARASHTRA',
    alertLevel: 'Red',
    eventType: 'STRUCTURAL FAILURE',
    lat: 19.2,
    lon: 72.9,
  },
  {
    id: `dummy-dummy-pax17b903`,
    title: 'MAJOR CIVIL_UNREST ALERT: BHAYANDERPADA, THANE',
    description: 'Violent land dispute involving 80-100 people. Iron rods and stones used, multiple injuries.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'BHAYANDERPADA, THANE, MAHARASHTRA',
    alertLevel: 'Orange',
    eventType: 'CIVIL_UNREST',
    lat: 19.2,
    lon: 72.9,
  },
  {
    id: `dummy-dummy-zb9i610lp`,
    title: 'MAJOR SECURITY ALERT: THANE',
    description: 'Police seized ₹1.4 crore worth drugs, 20+ arrests across Thane and Mira-Bhayandar zone.',
    severity: 'medium',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'THANE, MAHARASHTRA',
    alertLevel: 'Orange',
    eventType: 'SECURITY',
    lat: 19.2,
    lon: 72.9,
  },
  {
    id: `dummy-dummy-sazxhjrwg`,
    title: 'MAJOR INFRASTRUCTURE ALERT: THANE',
    description: '~150 families facing eviction near Railway Chawl due to unsafe proximity to railway.',
    severity: 'low',
    source: 'LOCAL_AUTHORITY // DUMMY_DATA',
    location: 'THANE, MAHARASHTRA',
    alertLevel: 'Yellow',
    eventType: 'INFRASTRUCTURE',
    lat: 19.2,
    lon: 72.9,
  },
];
